### ISSUE TITLE
setleds -v results in: Some state could not be determined. Please try running as root/sudo.

### ISSUE THREAD

**Issue by zachschultz** [damieng/setledsmac#10] opened 2018-07-02 20:13 UTC
I am running OSX 10.13.5, and when I try `setleds -v` or `sudo setleds -v` I get the following output:

```
SetLEDs version 0.2 - http://github.com/damieng/setledsmac

 "Karabiner VirtualHIDKeyboard"

 "Realforce 87" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.

 "(null)" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.

 "Apple Internal Keyboard / Trackpad" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.
```

**Comment by damieng** [comment] 2018-07-02 20:59
Duplicate of https://github.com/damieng/setledsmac/issues/7

**Closed by damieng** 2018-07-02 20:59 UTC
